spring.application.name=PASiR_Pecek_Maksymilian
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:mysql://localhost:3306/pecek_maksymilian_k03_spring?serverTimezone=UTC
spring.datasource.username=user-ni
spring.datasource.password=strongUserPass123!


spring.jpa.hibernate.ddl-auto=update

spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls
JWT_SECRET=${JWT_SECRET}